version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-jwt-auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres-jwt
